services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: devtrungk3
      MYSQL_DATABASE: project_management_db
    volumes:
      - project_management_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
volumes:
  project_management_data: